"""PyOpenAlex - A Pydantic-powered Python client for the OpenAlex API."""

from pyopenalex.client import OpenAlex
from pyopenalex.config import Settings
from pyopenalex.exceptions import (
    APIError,
    AuthenticationError,
    NotFoundError,
    OpenAlexError,
    RateLimitError,
)
from pyopenalex.expressions import between, gt, lt, ne, or_
from pyopenalex.models import (
    Author,
    Award,
    Continent,
    Country,
    Domain,
    Field,
    Funder,
    Institution,
    InstitutionType,
    Keyword,
    Language,
    License,
    Publisher,
    Sdg,
    Source,
    SourceType,
    Subfield,
    Topic,
    Work,
    WorkType,
)

__all__ = [
    "OpenAlex",
    "Settings",
    "APIError",
    "AuthenticationError",
    "NotFoundError",
    "OpenAlexError",
    "RateLimitError",
    "Author",
    "Award",
    "Continent",
    "Country",
    "Domain",
    "Field",
    "Funder",
    "Institution",
    "InstitutionType",
    "Keyword",
    "Language",
    "License",
    "Publisher",
    "Sdg",
    "Source",
    "SourceType",
    "Subfield",
    "Topic",
    "Work",
    "WorkType",
    "between",
    "gt",
    "lt",
    "ne",
    "or_",
]
